on: [push, pull_request]

name: build

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Install system libraries
        run: sudo apt-get update && sudo apt-get install -y  libxxhash-dev libzstd-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
      - uses: Swatinem/rust-cache@v1
      - run: cargo build --release --all-features --all-targets
